### ISSUE TITLE
研讨课 3

### ISSUE THREAD

**Issue by Vigilans** [Vigilans/TypeGL#4]
## 主题：多对象场景的变换和观察
* 运用计算机观察的知识实现场景漫游，讨论不同的函数所能实现的场景漫游效果的不同。
* 进一步完善对象的建模和绘制，要求：
  * 应用多边形网格的，不能直接使用第三方平台 
  * 应用简单对象进行组合的，一个场景对象至少要由3个简单对象组合而成。
* 实现相机的变换，可以交互实现漫游； 
* （选做）自动沿规划路径运动
* （选做）给对象加上简单阴影

## Todo
- [x] 将数学运算逻辑嵌入至项目核心模块 (core文件夹) 中。 -- lsc
- [x] 将跟踪球逻辑嵌入至项目核心模块 (core文件夹) 中。 -- yzh
- [x] 实现上一次研讨中动物的“向前走”逻辑（只要给每个动物加一个uniform u_Direction属性，指向动物的当前朝向就差不多了）。-- yzh
- [x] 解决渲染性能问题（目前的渲染代码有问题，每一帧都会向Buffer里重新传一次数据）-- yzh
- [x] 添加第三只动物 -- lsc/yzh
- [x] 绘制阴影对象 -- lsc
- [x] 第三只动物的独立运动 -- lsc
