### ISSUE TITLE
研讨课 4

### ISSUE THREAD

**Issue by Vigilans** [Vigilans/TypeGL#6]
## 主题：光照和明暗绘制 
* 掌握光照和明暗绘制的基本原理、设置步骤，并讨论实验效果与参数设置的关系 
* 场景中加入光照，要求：
  * 光源位置可交互改变
  * 场景中至少包含两种以上的材质
  * 附加要求：在场景中绘制出光源

## Todo List:
- [x] 画平面的API -- yzh
- [x] 画球的API（我们到现在才做。。。） -- yzh
- [x] 为光源这种没有朝向、法向量的Object定义一种新Controller -- yzh
- [x] 实现光照效果 -- lsc
- [x] 让光源绕z轴转动，实现光照和阴影的动态效果 -- yzh
- [x] Optional: 修复那个贝塞尔鱼的bug -- yzh
- [x] Optional: 调教好Camera -- yzh
- [ ] ~~Optional: 实现那个高级版阴影逻辑~~（留给下一次了）
